import type { Categoria } from '../types'

export const CATEGORIAS: Categoria[] = [
  {
    id: 'aceros',
    nombre: 'Aceros',
    icono: '⚙️',
    color: '#7f8c8d',
    referencias: [
      { codigo: '10001', descripcion: 'CHATARRA DE ACERO' },
      { codigo: '10003', descripcion: 'CHATARRA DE ACERO LIMAYA' },
      { codigo: '10004', descripcion: 'CHATARRA DE ACERO 201' },
      { codigo: '10005', descripcion: 'CHATARRA DE ACERO 316' },
      { codigo: '10007', descripcion: 'CHATARRA DE ACERO ESPECIAL' },
      { codigo: '10013', descripcion: 'CHATARRA DE ACERO VOLUMINOSO' },
      { codigo: '10020', descripcion: 'CHATARRA DE ACERO ALLOYB X' },
      { codigo: '10021', descripcion: 'CHATARRA DE ACERO ALLOY 825' },
      { codigo: '10023', descripcion: 'CHATARRA DE ACERO NITRONIC 50' },
      { codigo: '10024', descripcion: 'CHATARRA DE ACERO ALLOY 718' },
      { codigo: '10025', descripcion: 'CHATARRA DE ACERO ALLOY 800' },
      { codigo: '10029', descripcion: 'CHATARRA DE ACERO ALLOY 400' },
      { codigo: '10034', descripcion: 'CHATARRA DE ACERO NI-200' },
      { codigo: '10035', descripcion: 'CHATARRA DE ACERO ALLOYD 738' },
      { codigo: '10045', descripcion: 'CHATARRA DE FILTRO DE ACERO' },
      { codigo: '10050', descripcion: 'CHATARRA DE ACERO ALLOYD 617 CON ZIRCONIO' },
      { codigo: '10055', descripcion: 'CHATARRA DE ACERO ALLOYD X CON ZIRCONIO' },
      { codigo: '10057', descripcion: 'CHATARRA DE ACERO ESPECIAL NI RESIST' },
    ],
  },
  {
    id: 'aluminios',
    nombre: 'Aluminios',
    icono: '⚪',
    color: '#bdc3c7',
    referencias: [
      { codigo: '11002', descripcion: 'CHATARRA DE ALUMINIO OLLA' },
      { codigo: '11027', descripcion: 'CHATARRA ALUMINIO OLLA PRESION' },
      { codigo: '11003', descripcion: 'CHATARRA DE ALUMINIO PERFIL' },
      { codigo: '11037', descripcion: 'CHATARRA DE ALUMINIO PERFIL SUCIO' },
      { codigo: '11045', descripcion: 'CHATARRA ALUMINIO PERFIL PINTADO' },
      { codigo: '11034', descripcion: 'CHATARRA DE ALUMINIO PERFIL PICADILLO' },
      { codigo: '11035', descripcion: 'CHATARRA DE ALUMINIO (E) 6061' },
      { codigo: '11004', descripcion: 'CHATARRA DE ALUMINIO BLANDO' },
      { codigo: '11033', descripcion: 'CHATARRA DE ALUMINIO BLANDO VOLUMEN' },
      { codigo: '11005', descripcion: 'CHATARRA DE ALUMINIO GRUESO' },
      { codigo: '11024', descripcion: 'CHATARRA DE ALUMINIO GRUESO TIPO 2' },
      { codigo: '11028', descripcion: 'CHATARRA DE ALUMINIO GRUESO TIPO 3' },
      { codigo: '11032', descripcion: 'CHATARRA DE ALUMINIO GRUESO VOLUMEN' },
      { codigo: '11006', descripcion: 'CHATARRA DE RADIADOR DE ALUMINIO' },
      { codigo: '11031', descripcion: 'CHATARRA DE RADIADOR DE ALUMINIO SUCIO' },
      { codigo: '11007', descripcion: 'CHATARRA DE ALUMINIO POTE SALCHICHA' },
      { codigo: '11008', descripcion: 'CHATARRA DE POTE PERFUMERO' },
      { codigo: '11010', descripcion: 'CHATARRA DE ALUMINIO LITOGRAFICO' },
      { codigo: '11011', descripcion: 'CHATARRA DE ALUMINIO ALAMBRON' },
      { codigo: '11016', descripcion: 'CHATARRA DE ALUMINIO RIN' },
      { codigo: '11017', descripcion: 'CHATARRA DE ALUMINIO REVUELTO' },
      { codigo: '11019', descripcion: 'CHATARRA DE ALUMINIO RIN BICICLETA' },
      { codigo: '11026', descripcion: 'CHATARRA DE ALUMINIO RIN CAMION' },
      { codigo: '11040', descripcion: 'CHATARRA GUAYA DE ALUMINIO ENCAUCHETADA' },
      { codigo: '11043', descripcion: 'CHATARRA DE ALUMINIO RIN AUTO CON VALVULAS' },
      { codigo: '28001', descripcion: 'CHATARRA DE ZINC' },
    ],
  },
  {
    id: 'pote',
    nombre: 'POTE',
    icono: '🥫',
    color: '#95a5a6',
    referencias: [
      { codigo: '11001', descripcion: 'CHATARRA DE ALUMINIO POTE' },
      { codigo: '11046', descripcion: 'POTE BRIQUETEADO' },
    ],
  },
  {
    id: 'bronce',
    nombre: 'BRONCE',
    icono: '🟠',
    color: '#cd7f32',
    referencias: [
      { codigo: '13001', descripcion: 'CHATARRA DE BRONCE' },
      { codigo: '13002', descripcion: 'BRONCE LATON 70/30 - 2' },
      { codigo: '13003', descripcion: 'BRONCE FOSFORADO' },
      { codigo: '13005', descripcion: 'CHATARRA DE BRONCE 70/30' },
      { codigo: '13009', descripcion: 'CHATARRA DE BRONCE SUCIO' },
      { codigo: '13012', descripcion: 'CHATARRA DE BRONCE TIPO 2' },
      { codigo: '13013', descripcion: 'CHATARRA DE BRONCE 80/20' },
      { codigo: '13014', descripcion: 'CHATARRA DE BRONCE 90/10' },
      { codigo: '17001', descripcion: 'CHATARRA DE LIMAYA DE BRONCE' },
      { codigo: '22001', descripcion: 'BRONCE SUCIO' },
      { codigo: '24001', descripcion: 'CHATARRA DE CUPRONIQUEL' },
      { codigo: '24003', descripcion: 'CHATARRA DE CUPRONIQUEL 90/10' },
      { codigo: '24002', descripcion: 'CHATARRA DE CUPRONIQUEL 70/30' },
    ],
  },
  {
    id: 'cobre',
    nombre: 'Cobre',
    icono: '🟤',
    color: '#b87333',
    referencias: [
      { codigo: '15001', descripcion: 'CHATARRA DE COBRE No 1' },
      { codigo: '15002', descripcion: 'CHATARRA DE COBRE BRILLANTE' },
      { codigo: '15003', descripcion: 'CHATARRA DE COBRE No. 2' },
      { codigo: '15004', descripcion: 'CHATARRA DE COBRE ENCAUCHETADO' },
      { codigo: '15027', descripcion: 'CHATARRA DE COBRE 1C' },
      { codigo: '15048', descripcion: 'CHATARRA CABLE DE COBRE EMPALMES' },
      { codigo: '15065', descripcion: 'CHATARRA CABLE DE PLOMO LIMPIO' },
      { codigo: '15066', descripcion: 'CHATARRA CABLE DE COBRE CON CUBIERTA DE PAPEL 0.4' },
      { codigo: '15076', descripcion: 'CHATARRA DE COBRE MULTICOLOR SECO' },
      { codigo: '15079', descripcion: 'CHATARRA DE COBRE TELEFONICA' },
      { codigo: '15096', descripcion: 'CHATARRA DE CABLE DE COBRE AISLADO' },
      { codigo: '15114', descripcion: 'CHATARRA DE INTERCOOLER DE HIERRO CON COBRE' },
      { codigo: '15116', descripcion: 'CHATARRA DE TUBERIA Y VALVULA DE COBRA' },
      { codigo: '15117', descripcion: 'CHATARRA DE COBRE SUCIO' },
      { codigo: '15118', descripcion: 'CHATARRA DE COBRE VARIADO' },
      { codigo: '15119', descripcion: 'CHATARRA DE CABLES DE COBRE' },
      { codigo: '15123', descripcion: 'CHATARRA DE GUAYA DE COBRE' },
      { codigo: '15124', descripcion: 'CHATARRA DE TUBERIA DE COBRE' },
    ],
  },
  {
    id: 'radiadores_cobre',
    nombre: 'Radiadores de Cobre',
    icono: '🔴',
    color: '#e74c3c',
    referencias: [
      { codigo: '19001', descripcion: 'CHATARRA DE RADIADOR DE COBRE' },
      { codigo: '19003', descripcion: 'CHATARRA DE RADIADOR DE COBRE SUCIO' },
      { codigo: '261062', descripcion: 'CHATARRA DE INTERCOOLER' },
    ],
  },
  {
    id: 'radiadores_mixtos',
    nombre: 'Radiadores Mixtos',
    icono: '🔶',
    color: '#e67e22',
    referencias: [
      { codigo: '19002', descripcion: 'CHATARRA DE RADIADOR MIXTO' },
      { codigo: '19004', descripcion: 'CHATARRA DE RADIADOR MIXTO SUCIO' },
    ],
  },
  {
    id: 'scrap',
    nombre: 'SCRAP',
    icono: '🗑️',
    color: '#2c3e50',
    referencias: [
      { codigo: '18001', descripcion: 'DESP. Y DESEC. DE PLOMO CASCARA' },
      { codigo: '18004', descripcion: 'DESP. Y DESEC. DE SCRAP DE MOTO' },
      { codigo: '18005', descripcion: 'DESP. Y DESEC. DE SCRAP LIMPIO' },
      { codigo: '18007', descripcion: 'DESP. Y DESEC. DE PLOMO BALANCIN' },
      { codigo: '18009', descripcion: 'SCRAP SECO PEQUEÑO' },
      { codigo: '18010', descripcion: 'SCRAP SECO GRANDE' },
    ],
  },
  {
    id: 'baterias',
    nombre: 'BATERIAS',
    icono: '🔋',
    color: '#27ae60',
    referencias: [
      { codigo: '14001', descripcion: 'DESPERDICIO DE BATERIA No. 7' },
      { codigo: '14002', descripcion: 'DESPERDICIO DE BATERIA No. 8' },
      { codigo: '14003', descripcion: 'DESPERDICIO DE BATERIA No. 1' },
      { codigo: '14004', descripcion: 'DESPERDICIO DE BATERIA No. 2' },
      { codigo: '14005', descripcion: 'DESPERDICIO DE BATERIA No. 3' },
      { codigo: '14006', descripcion: 'DESPERDICIO DE BATERIA No. 4' },
      { codigo: '14007', descripcion: 'DESPERDICIO DE BATERIA No. 5' },
    ],
  },
  {
    id: 'electronica',
    nombre: 'ELECTRONICA',
    icono: '💻',
    color: '#8e44ad',
    referencias: [
      { codigo: '26002', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 4 AMARILLA VERDE' },
      { codigo: '26003', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 4A AMARILLA VERDE' },
      { codigo: '26004', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 4 A COLORES' },
      { codigo: '26005', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 4 B VERDE AMARILLA' },
      { codigo: '26006', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 4 B B COLORES' },
      { codigo: '26007', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 3 COLORES' },
      { codigo: '26009', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TIPO 1' },
      { codigo: '26010', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TIPO 2 A' },
      { codigo: '26012', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TIPO 3' },
      { codigo: '26013', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE PORTATIL' },
      { codigo: '26014', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE SERVIDOR GRANDE' },
      { codigo: '26015', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE SERVIDOR PEQUEÑA' },
      { codigo: '26016', descripcion: 'CHATARRA ELECTRONICA DE TARJETA LECTORA' },
      { codigo: '26017', descripcion: 'CHATARRA DE TARJETA ELECTRONICA BAJO GRADO MARRON' },
      { codigo: '26018', descripcion: 'CHATARRA DE TARJETA ELECTRONICA BAJO GRADO VERDE' },
      { codigo: '26020', descripcion: 'CHATARRA DE TARJETA ELECTRONICA CENTRAL PLACA DORADO' },
      { codigo: '26021', descripcion: 'CHATARRA DE RAJETA ELECTRONICA CENTRAL POBLADA' },
      { codigo: '26022', descripcion: 'CHATARRA DE TARJETA ELECTRONICA CENTRAL' },
      { codigo: '26023', descripcion: 'CHATARRA DE TARJETA ELECTRONICA FILO DORADO' },
      { codigo: '26026', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TABLON MACHO' },
      { codigo: '26027', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TABLON MACHO DESPOBLADO' },
      { codigo: '26028', descripcion: 'CHATARRA ELECTRONICA PROCESADOR PEQUEÑO CON PINES' },
      { codigo: '26029', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE DISCO DURO' },
      { codigo: '26030', descripcion: 'CHATARRA ELECTRONICA DE MEMORIA RAM DORADO' },
      { codigo: '26031', descripcion: 'CHATARRA ELECTRONICA DE MEMORIA RAM PLATEADA' },
      { codigo: '26032', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE CELULAR SMARTPHONES' },
      { codigo: '26033', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE CELULAR CHINOS' },
      { codigo: '26034', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE CELULAR ANTIGUOS' },
      { codigo: '26035', descripcion: 'CHATARRA ELECTRONICA PROCESADOR PASTA CON BLINDAJE' },
      { codigo: '26036', descripcion: 'CHATARRA ELECTRONICA PROCESADOR PASTA SIN BLINDAJE' },
      { codigo: '26037', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 4 C VERDE AMARILLA' },
      { codigo: '26038', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 4 C COLORES' },
      { codigo: '26039', descripcion: 'CHATARRA DE TARJETA ELECTRONICA PENTIUM 4 TRES TORNILLOS' },
      { codigo: '26041', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE MODEM B' },
      { codigo: '26042', descripcion: 'CHATARRA DE TARJETA ELECTONICA FLEXIBLE' },
      { codigo: '26043', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE TABLE' },
      { codigo: '26044', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE CONTROL TV' },
      { codigo: '26047', descripcion: 'CHATARRA ELECTRONICA PINES DORADOS FINOS' },
      { codigo: '26049', descripcion: 'CHATARRA ELECTRONICA CD' },
      { codigo: '26052', descripcion: 'CHATARRA ELECTRONICA SLOT' },
      { codigo: '26053', descripcion: 'Ram modem (wifi)' },
      { codigo: '26055', descripcion: 'CHATARRA ELECTRONICA PROCESADOR PLASTICO NEGRO' },
      { codigo: '26056', descripcion: 'CHATARRA ELECTRONICA PROCESADOR CERAMICO ALUMINIO' },
      { codigo: '26057', descripcion: 'CHATARRA ELECTRONICA PROCESADOR CERAMICO' },
      { codigo: '26058', descripcion: 'CHATARRA ELECTRONICA DISCO DURO ENTERO' },
      { codigo: '26059', descripcion: 'CHATARRA ELECTRONICA DISCO DURO SIN TARJETA' },
      { codigo: '26060', descripcion: 'CHATARRA ELECTRONICA FUENTE DE PODER CON CABLE' },
      { codigo: '26061', descripcion: 'CHATARRA ELECTRONICA DE TABLE ENTERA' },
      { codigo: '26062', descripcion: 'CHATARRA ELECTRONICA DE CELULAR ENTERO' },
      { codigo: '26063', descripcion: 'CHATARRA ELECTRONICA DE PORTATIL ENTERO' },
      { codigo: '26064', descripcion: 'CHATARRA ELCTRONICA DE RADIOGRAFIA' },
      { codigo: '26066', descripcion: 'CHATARRA ELECTRONICA DE CELULAR ENTERO TACTIL' },
      { codigo: '26067', descripcion: 'BATERIA PORTATIL' },
      { codigo: '26068', descripcion: 'BATERIAL CELULAR' },
      { codigo: '26069', descripcion: 'CHATARRA DE TARJETA ELECTRONICA LINGOTE DORADO COBRE' },
      { codigo: '26070', descripcion: 'CHATARRA DE TARJETA ELECTRONICA LINGOTE DORADO/ PLATA' },
      { codigo: '26071', descripcion: 'CHATARRA DE TARJETA ELECTRONICA LINGOTE DORADO / PLATA OPACO' },
      { codigo: '26073', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE DECODIFICADOR BUENO' },
      { codigo: '26075', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE DECODIFICADOR MALO' },
      { codigo: '26076', descripcion: 'CHATARRA ELECTRONICA PROCESADOR CERAMICO CENTRO DORADO' },
      { codigo: '26077', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TABLON HEMBRA' },
      { codigo: '26078', descripcion: 'CHATARRA ELECTRONICA FUENTE DE PODER SIN CABLE' },
      { codigo: '26079', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TIPO 2 MIXTO 1 BANDERA' },
      { codigo: '26080', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TIPO 2 BANDERA' },
      { codigo: '26081', descripcion: 'CHATARRA DE TARJETA ELECTRONICA MODEM BANDERA' },
      { codigo: '26082', descripcion: 'CHATARRA ELECTRONICA DE PORTATIL INCOMPLETO' },
      { codigo: '26083', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE PORTATIL CON BANDERA' },
      { codigo: '26091', descripcion: 'CHATARRA ELECTRONICA DE CELULAR ENTERO CHINO' },
      { codigo: '26092', descripcion: 'CHATARRA DE TARJETA ELETRONICA DE CELULAR TACTIL' },
      { codigo: '26093', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TIPO 2' },
      { codigo: '26100', descripcion: 'CHATARRA DE TARJETA ELECTRONICA TIPO 2 PLUS' },
      { codigo: '26105', descripcion: 'CHATARRA ELECTRONICA DE MEMORIA RAM DOS CARAS' },
      { codigo: '26108', descripcion: 'CHATARRA ELECTRONICA DE BATERIA LITIO' },
      { codigo: '26109', descripcion: 'CHATARRA ELECTRONICA DE CELULAR ENTERO CHINO' },
      { codigo: '26110', descripcion: 'CHATARRA ELECTRONICA DE TARJETA DE CELULAR BLACKBERRY' },
      { codigo: '26112', descripcion: 'CHATARRA DE EQUIPOS ELECTRICOS Y ELECTRONICOS' },
      { codigo: '26121', descripcion: 'TRITURADO ESPECIAL' },
      { codigo: '16004', descripcion: 'CHATARRA ELECTRONICA' },
    ],
  },
  {
    id: 'chatarra_hierro',
    nombre: 'CHATARRA DE HIERRO',
    icono: '🪨',
    color: '#34495e',
    referencias: [
      { codigo: '16002', descripcion: 'CHATARRA CORRIENTE 720430' },
      { codigo: '16003', descripcion: 'CHATARRA MIXTA' },
      { codigo: '21001', descripcion: 'BASURA' },
      { codigo: '21004', descripcion: 'CAUCHO' },
      { codigo: '21005', descripcion: 'MERMA QUEMADA' },
      { codigo: '21009', descripcion: 'ACEITE' },
      { codigo: '21015', descripcion: 'ARENA DEL ALUM BLANDO' },
      { codigo: '23002', descripcion: 'UNIDADES DE REFRIGERACION' },
      { codigo: '25001', descripcion: 'ARCHIVO' },
      { codigo: '11025', descripcion: 'CHATARRA DE ALUMINIO GALILLO' },
    ],
  },
]

export const CATEGORIA_MAP = new Map(CATEGORIAS.map(c => [c.id, c]))

export const MATERIALES = CATEGORIAS.map(c => ({
  id: c.id,
  nombre: c.nombre,
  codigo: c.id.toUpperCase(),
  icono: c.icono,
  color: c.color,
}))

export const MATERIAL_MAP = new Map(MATERIALES.map(m => [m.id, m]))
